import "./globals.scss";
import { Mulish } from "next/font/google";
import Header from "@/components/LayoutComponents/Header";
import SideBar from "@/components/LayoutComponents/SideBar";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["400", "700", "200", "300", "500", "600", "800", "900"],
  display: "swap",
});

export const metadata = {
  title: "Dazzie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header />
        <SideBar />
        <div className="layout_children ml-[112px]">{children}</div>
      </body>
    </html>
  );
}
